#!/hint/bash

die() {
	printf '%s\n' "$*" >&2
	exit 1
}

sd_user_ssh_L() {
	local config="$1"

	# resolve symlinks and normalize the path
	#
	config="$(realpath -- "$config")"

	local unit
	unit="ssh-L@$(systemd-escape --path -- "$config").service"

	if systemctl --user status -- "$unit" >/dev/null 2>&1; then
		return
	fi

	systemd-run \
		--user \
		-u "$unit" \
		-p Restart=always \
		-p RestartSec=5s \
		-p Type=forking \
		-- "${SSH[@]}" "${SSH_OPTS[@]}" \
			-fN \
			-L "$LOCAL_PORT:$REMOTE_HOST:$REMOTE_PORT" \
			-- "$SSH_HOST"
}
