#!/bin/bash

set -o errexit -o nounset -o pipefail

source -- "$(dirname -- "$(realpath -- "${BASH_SOURCE[0]}")")/lib"

if conf="$HOME/.mos.sh.conf"; [[ -f "$conf" && -r "$conf" ]]; then
	source -- "$conf"
fi

if (( $# < 1 )); then
	die "usage: $0 config [mariadb_options]"
fi

CONFIG="$HOME/.mos.sh.d/$1"
shift

if [[ ! -f "$CONFIG" || ! -r "$CONFIG" ]]; then
	die "bad config: $CONFIG"
fi

source -- "$CONFIG"

cmd=("${MARIADB[@]}" "${MARIADB_OPTS[@]}" "$@" -- "$REMOTE_DB")

if [[ -v SSH_HOST ]]; then
	sd_user_ssh_L "$CONFIG"
	exec_mariadb_over_proxy "${cmd[@]}"
else
	exec_mariadb "${cmd[@]}"
fi
