#!/bin/bash

set -o errexit -o nounset -o pipefail

mos_root_dir="$(dirname -- "$(realpath -- "${BASH_SOURCE[0]}")")"
source -- "$mos_root_dir/lib"
source -- "$mos_root_dir/default.conf"

if conf="$HOME/.mos.sh.conf"; [[ -f "$conf" && -r "$conf" ]]; then
	source -- "$conf"
fi

if (( $# < 1 )); then
	die "usage: $0 config [mariadb_options] [table_names]"
fi

CONFIG="$HOME/.mos.sh.d/$1"
shift

if [[ ! -f "$CONFIG" || ! -r "$CONFIG" ]]; then
	die "bad config: $CONFIG"
fi

source -- "$CONFIG"

cmd=("${MARIADB_DUMP[@]}" "${MARIADB_DUMP_OPTS[@]}")
tables=()

for arg in "$@"; do
	if [[ "$arg" == '--' ]]; then
		shift
		for arg in "$@"; do
			tables+=("$arg")
		done
		break
	elif [[ "$arg" =~ ^- ]]; then
		cmd+=("$arg")
		shift
	else
		tables+=("$arg")
		shift
	fi
done

cmd+=(-- "$REMOTE_DB" "${tables[@]}")

if [[ -v SSH_HOST ]]; then
	sd_user_ssh_L "$CONFIG"
	exec_mariadb_over_proxy "${cmd[@]}"
else
	exec_mariadb "${cmd[@]}"
fi
