#!/bin/bash

set -o errexit -o nounset -o pipefail

mos_root_dir="$(dirname -- "$(realpath -- "${BASH_SOURCE[0]}")")"
source -- "$mos_root_dir/lib"
source -- "$mos_root_dir/default.conf"

#
# read mos.sh configuration
#

if conf="$HOME/.mos.sh.conf"; [[ -f "$conf" && -r "$conf" ]]; then
	source -- "$conf"
fi

#
# parse command-line arguments
#

if (( $# < 1 )); then
	die "usage: $0 config [redis_options]"
fi

CONFIG="$HOME/.ros.sh.d/$1"
shift

#
# validate & read the connection configuration
#

if [[ ! -f "$CONFIG" || ! -r "$CONFIG" ]]; then
	die "bad config: $CONFIG"
fi

source -- "$CONFIG"

#
# build redis command
#

cmd=("${REDIS[@]}")

if [[ -v SSH_HOST ]]; then
	cmd+=(
		-h localhost
		-p "$LOCAL_PORT"
	)
else
	cmd+=(
		-h "$REMOTE_HOST"
		-p "$REMOTE_PORT"
	)
fi

cmd+=(
	"${REDIS_OPTS[@]}"
	"$@"
)

#
# run ssh & redis-cli
#

if [[ -v SSH_HOST ]]; then
	sd_user_ssh_L "$CONFIG"
fi

exec -- "${cmd[@]}"
